'\" t
.\"     Title: gpxlogger
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 6 December 2020
.\"    Manual: GPSD Documentation
.\"    Source: The GPSD Project
.\"  Language: English
.\"
.TH "GPXLOGGER" "1" "6 December 2020" "The GPSD Project" "GPSD Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gpxlogger \- Tool to connect to gpsd and generate a GPX file
.SH "SYNOPSIS"
.HP \w'\fBgpxlogger\fR\ 'u
\fBgpxlogger\fR [\-?] [\-\-daemonize] [\-\-debug\ \fIdebug\-level\fR] [\-\-export\ \fIexport\-method\fR] [\-\-exports] [\-\-help] [\-\-interval\fItrack\ timeout\fR] [\-\-minmove\ \fIminmove\fR] [\-\-output\ \fIfilename\fR] [\-\-version] [\-d] [\-D\ \fIdebug\-level\fR] [\-e\ \fIexport\-method\fR] [\-f\ \fIfilename\fR] [\-h] [\-i\ \fItrack\ timeout\fR] [\-l] [\-m\ \fIminmove\fR] [\-V] [\fIserver\fR [\fI:port\fR [\fI:device\fR]]]
.SH "DESCRIPTION"
.PP
This program collects fixes from
gpsd
and logs them to standard output in GPX, an XML profile for track logging\&.
.PP
The output may be composed of multiple tracks\&. A new track is created if there\*(Aqs no fix written for an interval specified by the
\fB\-i, \-\-interval\fR
and defaulting to 5 seconds\&.
.PP
gpxlogger
can use any of the export methods that
gpsd
supports\&. For a list of these methods, use the
\fB\-l, \-\-exports\fR\&. To force the method, give the
\fB\-e, \-\-export\fR
one of the colon\-terminated method names from the
\fB\-l, \-\-exports\fR
table\&.
.SH "OPTIONS"
.PP
\fB\-?\fR, \fB\-h\fR, \fB\-\-help\fR
.RS 4
Print a summary of options and then exit\&.
.RE
.PP
\fB\-d\fR, \fB\-\-daemonize\fR
.RS 4
Run as a daemon in background\&. It requires the
\fB\-f, \-\-output\fR
option, which directs output to a specified logfile\&.
.RE
.PP
\fB\-D LVL\fR, \fB\-\-debug LVL\fR
.RS 4
Sets the debug level; it is primarily for troubleshooting\&. It enables various progress messages to standard error\&.
.RE
.PP
\fB\-e METHOD\fR, \fB\-\-export METHOD\fR
.RS 4
If D\-Bus support is available on the host, GPSD is configured to use it, and
\fB\-e dbus, \-\-export dbus\fR
is specified, this program listens to DBUS broadcasts from
gpsd
via org\&.gpsd\&.fix\&.
.sp
With
\fB\-e sockets\fR, or if sockets is the method defaulted to, you may give a server\-port\-device specification as arguments\&.
.sp
The sockets default is to all devices on the localhost, using the default GPSD port 2947\&. An optional argument to any client may specify a server to get data from\&. A colon\-separated suffix is taken as a port number\&. If there is a second colon\-separated suffix, that is taken as a specific device name to be watched\&. However, if the server specification contains square brackets, the part inside them is taken as an IPv6 address and port/device suffixes are only parsed after the trailing bracket\&. Possible cases look like this:
.PP
localhost:/dev/ttyS1
.RS 4
Look at the default port of localhost, trying both IPv4 and IPv6 and watching output from serial device 1\&.
.RE
.PP
example\&.com:2317
.RS 4
Look at port 2317 on example\&.com, trying both IPv4 and IPv6\&.
.RE
.PP
71\&.162\&.241\&.5:2317:/dev/ttyS3
.RS 4
Look at port 2317 at the specified IPv4 address, collecting data from attached serial device 3\&.
.RE
.PP
[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:2317:/dev/ttyS5
.RS 4
Look at port 2317 at the specified IPv6 address, collecting data from attached serial device 5\&.
.RE
.sp
With
\fB\-e shm, \-\-export shm\fR
this program will listen to the local
gpsd
using shared memory\&.
.RE
.PP
\fB\-i SECONDS\fR, \fB\-\-interval SECONDS\fR
.RS 4
A new track is created if there\*(Aqs no fix written for an interval of SECONDS\&. Defaulting to 5 seconds\&.
.RE
.PP
\fB\-l\fR, \fB\-\-exports\fR
.RS 4
List all possible options for
\fB\-e, \-\-export\fR\&.
.RE
.PP
\fB\-m MINMOVE\fR, \fB\-\-minmove MINMOVE\fR
.RS 4
Sets a minimum move distance in meters (it may include a fractional decimal part)\&. Motions shorter than this will not be logged\&.
.RE
.PP
\fB\-r\fR, \fB\-\-reconnect\fR
.RS 4
Retry when GPSd loses the fix\&. Without
\fB\-r\fR,
gpxlogger
would quit in this case\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Dump the package version and exit\&.
.RE
.SH "SEE ALSO"
.PP
\fBgpsd\fR(8),
\fBgps\fR(1)
\fBgpspipe\fR(1)
.SH "AUTHORS"
.PP
Amaury Jacquot
<sxpert@sxpert\&.org>
& Petter Reinholdtsen
<pere@hungry\&.com>
& Chris Kuethe
<chris\&.kuethe@gmail\&.com>
