/*
 * Constants used for GPS time detection and rollover correction.
 *
 * Correct for week beginning 2019-06-27T00:00:00
 *
 * Autogenerated, do not edit. All changes will be undone.
 */
#define BUILD_CENTURY	2000
#define BUILD_WEEK	12                   # Assumes 10-bit week counter
#define BUILD_LEAPSECONDS	19
#define BUILD_ROLLOVERS	2         # Assumes 10-bit week counter

/* Autogenerated, do not edit. All changes will be undone. */
