#! /bin/sh /usr/share/dpatch/dpatch-run
## INSTALL-description-fix.dpatch by Bernd Zeimetz <bernd@bzed.de>
##
## DP: fixing the INSTALL description (aka TROUBLESHOOTING in the package)

@DPATCH@
--- a/INSTALL
+++ b/INSTALL
@@ -93,9 +93,9 @@ home directory or to the system-wide X a
 4. Start gpsd.  You'll need to give it as an argument a path to 
 a serial or USB port with a GPS attached to it.
 
-5. Once gpsd is running, telnet to port 2947.  Type 'f' to see what
-device it will query.  If you need to change the device, use 'f='
-to do so (see the manual page for details). Now plug in your GPS.
+5. Once gpsd is running, telnet to port 2947. By default gpsd will use
+/dev/ttyS0. If you need to change the device, use 'f=' to do so (see the
+manual page for details). Now plug in your GPS.
 
 6. Type "wr" to start raw and watcher modes.  You should see NMEA data
 (text lines beginning with $) spewing out.  You will also see lines
