#! /bin/sh /usr/share/dpatch/dpatch-run
## no-gps-manpage.dpatch by Bernd Zeimetz <bernd@bzed.de>
##
## DP: fixing pointers to gps(1), which is unfortunately provided by the 'gps' package

@DPATCH@
diff -urNad gpsd~/gps.xml gpsd/gps.xml
--- gpsd~/gps.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/gps.xml	2007-10-18 21:12:08.000000000 +0200
@@ -2,14 +2,13 @@
 <!DOCTYPE refentry PUBLIC 
    "-//OASIS//DTD DocBook XML V4.1.2//EN"
    "docbook/docbookx.dtd">
-<refentry id='gps.1'>
+<refentry id='xgps.1'>
 <refmeta>
-<refentrytitle>gps</refentrytitle>
+<refentrytitle>xgps</refentrytitle>
 <manvolnum>1</manvolnum>
 <refmiscinfo class='date'>9 Aug 2004</refmiscinfo>
 </refmeta>
 <refnamediv id='name'>
-<refname>gps</refname>
 <refname>xgps</refname>
 <refname>xgpsspeed</refname>
 <refname>cgps</refname>
diff -urNad gpsd~/gpsctl.xml gpsd/gpsctl.xml
--- gpsd~/gpsctl.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/gpsctl.xml	2007-10-18 21:11:20.000000000 +0200
@@ -140,7 +140,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgpsd</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>gpsprof</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
diff -urNad gpsd~/gpsd.xml gpsd/gpsd.xml
--- gpsd~/gpsd.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/gpsd.xml	2007-10-18 21:11:20.000000000 +0200
@@ -982,7 +982,7 @@
 </refsect1>
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgpsd</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>gpsprof</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
diff -urNad gpsd~/gpsfake.xml gpsd/gpsfake.xml
--- gpsd~/gpsfake.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/gpsfake.xml	2007-10-18 21:11:20.000000000 +0200
@@ -132,7 +132,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgpsd</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>gpsctl</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
diff -urNad gpsd~/gpsflash.xml gpsd/gpsflash.xml
--- gpsd~/gpsflash.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/gpsflash.xml	2007-10-18 21:11:20.000000000 +0200
@@ -90,7 +90,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgpsd</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>srec</refentrytitle><manvolnum>5</manvolnum></citerefentry>.
diff -urNad gpsd~/gpsprof.xml gpsd/gpsprof.xml
--- gpsd~/gpsprof.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/gpsprof.xml	2007-10-18 21:11:20.000000000 +0200
@@ -165,7 +165,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgpsd</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>gpsfake</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
diff -urNad gpsd~/libgps.xml gpsd/libgps.xml
--- gpsd~/libgps.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/libgps.xml	2007-10-18 21:11:20.000000000 +0200
@@ -181,7 +181,7 @@
 
 <para>The following is an excerpted and simplified version of the
 libgps interface code from
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>.
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>.
 The function <function>handle_input()</function> is a trivial pies of
 code that calls gps_poll(gpsdata).
 </para>
@@ -207,7 +207,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>.
 <citerefentry><refentrytitle>libgpsmm</refentrytitle><manvolnum>3</manvolnum></citerefentry>.
 </para>
diff -urNad gpsd~/libgpsd.xml gpsd/libgpsd.xml
--- gpsd~/libgpsd.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/libgpsd.xml	2007-10-18 21:11:20.000000000 +0200
@@ -162,7 +162,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgpsd</refentrytitle><manvolnum>3</manvolnum></citerefentry>.
 </para>
 </refsect1>
diff -urNad gpsd~/libgpsmm.xml gpsd/libgpsmm.xml
--- gpsd~/libgpsmm.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/libgpsmm.xml	2007-10-18 21:11:20.000000000 +0200
@@ -65,7 +65,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>.
 </para>
 </refsect1>
diff -urNad gpsd~/rtcm-104.xml gpsd/rtcm-104.xml
--- gpsd~/rtcm-104.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/rtcm-104.xml	2007-10-18 21:11:20.000000000 +0200
@@ -436,7 +436,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgpsd</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>gpsprof</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
diff -urNad gpsd~/rtcmdecode.xml gpsd/rtcmdecode.xml
--- gpsd~/rtcmdecode.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/rtcmdecode.xml	2007-10-18 21:11:20.000000000 +0200
@@ -89,7 +89,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgpsd</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>gpsprof</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
diff -urNad gpsd~/sirfmon.xml gpsd/sirfmon.xml
--- gpsd~/sirfmon.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/sirfmon.xml	2007-10-18 21:11:20.000000000 +0200
@@ -189,7 +189,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgpsd</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>gpsprof</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
diff -urNad gpsd~/srec.xml gpsd/srec.xml
--- gpsd~/srec.xml	2006-12-15 00:43:39.000000000 +0100
+++ gpsd/srec.xml	2007-10-18 21:11:20.000000000 +0200
@@ -283,7 +283,7 @@
 <refsect1 id='see_also'><title>SEE ALSO</title>
 <para>
 <citerefentry><refentrytitle>gpsd</refentrytitle><manvolnum>8</manvolnum></citerefentry>,
-<citerefentry><refentrytitle>gps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
+<citerefentry><refentrytitle>cgps</refentrytitle><manvolnum>1</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgps</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>libgpsd</refentrytitle><manvolnum>3</manvolnum></citerefentry>,
 <citerefentry><refentrytitle>gpsfake</refentrytitle><manvolnum>1</manvolnum></citerefentry>.
